services:

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user1234"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./database/postgres-init:/docker-entrypoint-initdb.d:ro
      - ./var:/var/lib/postgresql/data:rw
    restart: unless-stopped
    ports:
      - "9432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'

  serve-backend:
    depends_on:
      postgres:
        condition: service_started
